# Generated by Django 3.1.14 on 2023-03-29 14:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrayToReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=100)),
            ],
        ),
    ]
